tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/services"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Another PostgreSQL diff tool
brew "apgdiff"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Modern, maintained replacement for ls
brew "eza"
# Command-line fuzzy finder written in Go
brew "fzf"
# Remote repository management made easy
brew "ghq"
# Distributed revision control system
brew "git"
# Interactive command-line tool for using emoji in commit messages
brew "gitmoji"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# C library and command-line programs providing a simple interface to inotify
brew "inotify-tools"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Generic command-line non-JVM Apache Kafka producer and consumer
brew "kcat"
# Small memory footprint, flexible web-server
brew "lighttpd", restart_service: true
# Pluggable Authentication Modules for Linux
brew "linux-pam"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
# Development kit for the Java programming language
brew "openjdk@17"
# Object-relational database system
brew "postgresql@14"
# Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
brew "prettier"
# Prettier daemon
brew "prettierd"
# Generic syntax highlighter
brew "pygments"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Manage complex tmux sessions easily
brew "tmuxinator"
# JavaScript package manager
brew "yarn"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Tracks most-used directories to make cd smarter
brew "z"
# Bash scripts that integrate bat with various command-line tools
brew "eth-p/software/bat-extras"

# vim:ft=ruby
