tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/services"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Emacs dependency management
brew "cask"
# Modern, maintained replacement for ls
brew "eza"
# Remote repository management made easy
brew "ghq"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Simple terminal UI for git commands
brew "lazygit"
# Apple Silicon Monitor Top written in Golang
brew "mactop"
# Mac App Store command-line interface
brew "mas"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Manage multiple Node.js versions
brew "nvm"
# Open Fortinet client for PPP+TLS VPN tunnel services
brew "openfortivpn"
# Fast, disk space efficient package manager
brew "pnpm"
# Object-relational database system
brew "postgresql@14", link: false
# Object-relational database system
brew "postgresql@17", link: true
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Cross-shell prompt for astronauts
brew "starship"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Manage complex tmux sessions easily
brew "tmuxinator"
# JavaScript package manager
brew "yarn"
# Read system manual pages using bat as the manual page formatter
brew "eth-p/software/bat-extras-batman"
# Chromium based browser
cask "arc"
# Window manager that organizes desktop applications into predefined zones
cask "bentobox"
# Image, video and clipboard optimiser
cask "clop"
# Databases and SQL IDE
cask "datagrip"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Elgato FACECAM configuration tool
cask "elgato-camera-hub"
# Download manager with a torrent client
cask "folx"
# HTTP and GraphQL Client
cask "insomnia"
# Menu bar manager
cask "jordanbaird-ice"
# GPU-based terminal emulator
cask "kitty"
# Software for Logitech devices
cask "logi-options+"
# Open-source, KeePass-client and password manager
cask "macpass"
# Handy utility to manage and customize the notch area
cask "notchnook"
# System and utility switches
cask "only-switch"
# Collaboration platform for API development
cask "postman"
# IDE for Python programming - Community Edition
cask "pycharm-ce"
# Control your tools with a few keystrokes
cask "raycast"
# Emoji picker optimised for blind people
cask "rocket"
# Displays all open files and sockets in use by all running processes
cask "sloth"
# System monitor for the menu bar
cask "stats"
# Open-source code editor
cask "visual-studio-code"
# Rust-based terminal
cask "warp"
# Gecko based web browser
cask "zen-browser"
mas "Boom 3D", id: 1233048948
mas "ColorSlurp", id: 1287239339
mas "DevCleaner", id: 1388020431
mas "Dynamic wallpaper", id: 1582358382
mas "Enchanted", id: 6474268307
mas "Free Ruler", id: 1483172210
mas "Hand Mirror", id: 1502839586
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "MonitorControlLite", id: 1595464182
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PastePal", id: 1503446680
mas "Redis Insight", id: 6446987963
mas "S3", id: 6447647340
mas "Widgetter", id: 1553223588
mas "Xcode", id: 497799835
vscode "aaron-bond.better-comments"
vscode "alefragnani.bookmarks"
vscode "andenetalexander.vim-cheatsheet"
vscode "apollographql.vscode-apollo"
vscode "asvetliakov.vscode-neovim"
vscode "catppuccin.catppuccin-vsc"
vscode "chakrounanas.turbo-console-log"
vscode "chouzz.vscode-better-align"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "foxundermoon.shell-format"
vscode "golang.go"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-execution"
vscode "graphql.vscode-graphql-syntax"
vscode "gruntfuggly.todo-tree"
vscode "ionutvmi.path-autocomplete"
vscode "janisdd.vscode-edit-csv"
vscode "johnnymorganz.stylua"
vscode "johnpapa.vscode-peacock"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "kumar-harsh.graphql-for-vscode"
vscode "leetcode.vscode-leetcode"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mechatroner.rainbow-csv"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-edgedevtools.vscode-edge-devtools"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.js-debug-nightly"
vscode "ms-vscode.makefile-tools"
vscode "ms-vsliveshare.vsliveshare"
vscode "naumovs.color-highlight"
vscode "orta.vscode-jest"
vscode "pkief.material-icon-theme"
vscode "plex.vscode-protolint"
vscode "pnp.polacode"
vscode "redhat.vscode-yaml"
vscode "riazxrazor.html-to-jsx"
vscode "ritwickdey.liveserver"
vscode "shardulm94.trailing-spaces"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "steoates.autoimport"
vscode "sumneko.lua"
vscode "timonwong.shellcheck"
vscode "vintharas.learn-vim"
vscode "wayou.vscode-todo-highlight"
vscode "wix.vscode-import-cost"
vscode "xabikos.javascriptsnippets"
vscode "yzhang.markdown-all-in-one"
vscode "zhuangtongfa.material-theme"
vscode "zxh404.vscode-proto3"

# vim:ft=ruby
