function exists() {
  # `command -v` is similar to `which`
  # https://stackoverflow.com/a/677212/1341838
  command -v $1 >/dev/null 2>&1

  # More explicitly written:
  # command -v $1 1>/dev/null 2>/dev/null

  # File Descriptor (for redirecting command output):
  # STDIN  (Keyboard) = 0
  # STDOUT (Display)  = 1
  # STDERR (Display)  = 2
}

function cc() {
  clear
  tmux clear-history
}
