# Specify OS first
[[ -f /etc/os-release ]] && source /etc/os-release

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  alias-finder               # try `als` for self-explanation
  aliases                    # all good shortcuts (e.g. `glola` `glods` `gf` `gl`)
  aws
  colored-man-pages
  docker
  git
  history-substring-search
  kubectl
  vi-mode
  z
  zsh-autosuggestions
  zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
# export LANGUAGE=en_US.UTF-8
# export NCURSES_NO_UTF8_ACS=1

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

bindkey '^e' autosuggest-accept
bindkey '^L' vi-forward-word
bindkey '^k' up-line-or-search
bindkey '^j' down-line-or-search
bindkey '^A' autosuggest-toggle

zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes # disabled by default

# =========================   PERSONAL CONFIG   ================================

# Set Variables
# Syntax highlighting for man pages using bat
# export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export TZ=Asia/Bangkok
export EDITOR="nvim"
export TERMINAL="kitty"

# USE NVIM as VISUAL EDITOR: https://unix.stackexchange.com/a/501863
export VISUAL="$EDITOR"
export BROWSER="firefox"

export HOMEBREW_CASK_OPTS="--no-quarantine"
export NULLCMD=bat
export LESS='--quit-if-one-screen --ignore-case --status-column --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init --window=-4 --mouse --wheel-lines=5'
export MANWIDTH_RIGHT_OFFSET=8

# Change ZSH Options

# Create Aliases
alias rl='omz reload'
alias ls='eza -lah --git'
alias eza='eza -lah --git'
alias man="update_man_width;BAT_THEME='Monokai Extended' batman '$@'"
alias trail='<<<${(F)path}'
alias szsh='source ~/.zshrc'
alias lg='lazygit'
alias mk='make'

# useful copy and travel path across terminal
alias pwdc='echo -n $(pwd) | clipcopy'

# pick by fcsonline/tmux-thumbs
# TODO: USE THIS SOLUTION INSTEAD: https://sw.kovidgoyal.net/kitty/kittens/hints/#

# My most frequently accessed directories (for simply, try using: `als cd`, `als nv`)
alias cda='cd ~/dotfiles/arch/'
alias cdc='cd ~/dotfiles/config/'
alias cdd='cd ~/dotfiles/'
alias cdk='cd ~/vaults/second-brain/'
alias cdw='cd ~/Works'
alias cdv='cd ~/dotfiles/config/nvim/'
alias cdz='cd ~/dotfiles/zsh'

alias  nv='nvim'
alias nva='nvim ~/dotfiles/arch/'
alias nvc='nvim ~/dotfiles/config/'
alias nvd='nvim ~/dotfiles/'
alias nvk='nvim ~/vaults/second-brain/'
alias nvv='nvim ~/dotfiles/config/nvim/'
alias nvz='nvim ~/dotfiles/zsh/zshrc'

# DevOps tools aliases
alias dcb='docker compose build'
alias dcu='docker compose up -d'
alias dcd='docker compose down'
alias dcw='docker compose watch'

# Customize Prompt(s)
# PROMPT='
# %1~ %L %# '
#
# RPROMPT='%*'

# Add Locations to $PATH Variable (See also: https://unix.stackexchange.com/a/26059)
export CARGOPATH="$HOME/.cargo/bin"
export PATH=$PATH:$CARGOPATH

# Write Handy Functions
function mkcd() {
  mkdir -p "$@" && cd "$_"
}

function update_man_width() {
  # See also: https://unix.stackexchange.com/questions/215584/whats-the-name-of-the-environment-variable-with-current-terminal-width

  # WAYS TO GET TERMINAL SIZES ()
  # 1.with env $COLUMNS and $LINES
  # 2.with stty `echo $(stty size) | awk '{print $2}'`
  # 3.with tput `tput {cols,lines}` (it's run non-interactive shell and got 80)

  # Using expr: https://unix.stackexchange.com/questions/480121/simple-command-line-calculator
  export MANWIDTH="$(expr $COLUMNS - $MANWIDTH_RIGHT_OFFSET)"
}

# Use ZSH Plugins

# ...Other Surprises

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source ~/dotfiles/zsh/env/go.sh

source ~/dotfiles/zsh/scripts/nvm.sh
source ~/dotfiles/zsh/scripts/git.sh
source ~/dotfiles/zsh/scripts/brew.sh
